# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'verbose_name': 'Home Carousel', 'verbose_name_plural': 'Home Carousel Slides'},
        ),
    ]
