# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180613_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('marquee_image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Maruqee Image for SubCategory page', null=True)),
                ('list_image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Image used in product categories page', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Category')),
            ],
        ),
    ]
