# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180619_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Maruqee Image for SubCategory page', null=True)),
                ('description', models.TextField()),
                ('availability_cta', models.TextField()),
                ('is_featured_on_homepage', models.BooleanField()),
                ('is_featured_on_landing', models.BooleanField(help_text='Check if this recipe should be displayed in featured product module on product landing page')),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
