# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180809_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured_on_homepage',
            field=models.BooleanField(help_text='Check if this product should be featured on the product landing page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured_on_landing',
            field=models.BooleanField(help_text='Check if this product should be displayed in featured product module on product landing page'),
        ),
    ]
