# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 23:56
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180809_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
