# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180815_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.CharField(blank=True, help_text='Ex. 130', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.CharField(blank=True, help_text='Ex. 24g', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cholestrol',
            field=models.CharField(blank=True, help_text='Ex. 0mg', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.CharField(blank=True, help_text='Ex. 5g', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.CharField(blank=True, help_text='Ex. 3g', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trans_fat',
            field=models.CharField(blank=True, help_text='Ex. 0g', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_id',
            field=models.CharField(blank=True, help_text='Video ID for video, e.g. https://www.youtube.com/watch?v=7NONdwbqRV8, id would be 7NONdwbqRV8', max_length=255, null=True),
        ),
    ]
