# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gluten_free',
            field=models.BooleanField(default=False, help_text='Show the GF logo'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_artificial_colors',
            field=models.BooleanField(default=False, help_text='Show no artificial colors logo'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_artificial_flavors',
            field=models.BooleanField(default=False, help_text='Show no artificial flavors logo'),
        ),
    ]
