# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20180825_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Marquee Image', null=True)),
                ('is_featured_on_landing', models.BooleanField(help_text='Check if this collection should be displayed in featured collection carousel on recipe landing page')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('fraction', models.CharField(blank=True, choices=[('quarter', '1/4'), ('third', '1/3'), ('half', '1/2'), ('two-thirds', '2/3'), ('three-quarters', '3/4')], max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Marquee Image', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, help_text='Marquee Image', null=True)),
                ('video_id', models.CharField(blank=True, help_text='Video ID for video, e.g. https://www.youtube.com/watch?v=7NONdwbqRV8, id would be 7NONdwbqRV8', max_length=255, null=True)),
                ('prep_time', models.CharField(max_length=100)),
                ('cook_time', models.CharField(max_length=100)),
                ('makes', models.CharField(max_length=100)),
                ('nutrition', models.CharField(max_length=100)),
                ('collections', models.ManyToManyField(to='web.Collection')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='marquee_image',
            field=pyuploadcare.dj.models.ImageField(blank=True, help_text='Marquee Image for SubCategory page', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_instruction', to='web.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='web.Recipe'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_recipe', to='web.Recipe'),
        ),
    ]
