# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 20:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180828_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The average rating the Sprinklr Service returned for this recipe', max_digits=5),
        ),
    ]
