# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_recipe_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='The title careers page will have.', max_length=200)),
                ('text', models.TextField(help_text='Description text about the careers page.')),
                ('cta_text', models.CharField(help_text='Text on the button that will redirect user to open positions.', max_length=32)),
                ('cta_url', models.URLField(help_text='Open positions url.')),
                ('legal_copy', models.TextField(help_text='Legal verbatim.')),
            ],
        ),
    ]
