# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20180926_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Question', 'verbose_name_plural': 'FAQ Questions'},
        ),
    ]
