# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20181002_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=''))
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
