# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_historypage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historypage',
            options={'ordering': ['date'], 'verbose_name': 'Our History Page', 'verbose_name_plural': 'Our History Page'},
        ),
        migrations.AddField(
            model_name='historypage',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Show just year i.e 2018'), (2, 'Show just month i.e January'), (3, 'Show month and year i.e Jan, 2018')], default=1),
        ),
    ]
