# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20181009_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='marquee_image',
            field=models.ImageField(blank=True, help_text='Marquee Image for Category page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, help_text='Marquee Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historypage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image of carousel slide', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Marquee Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary product image used on detail and landing pages', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_facts',
            field=models.ImageField(blank=True, help_text='Used to display nutritional facts label', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Marquee Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_facts',
            field=models.ImageField(blank=True, help_text='Used to display nutritional facts label', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='list_image',
            field=models.ImageField(blank=True, help_text='Image used in product categories page', null=True, upload_to=''),
        ),
    ]
