# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20181017_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_influencer_title', models.CharField(max_length=100)),
                ('featured_influencer_description', models.TextField(blank=True, null=True)),
                ('featured_influencer_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
