# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_product_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_recipe_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_recipe_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
