# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20181108_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(blank=True, choices=[('gluten-free', 'Gluten-free'), ('vegetarian', 'Vegetarian'), ('popular', 'Most Popular'), ('kid-friendly', 'Kid Friendly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cook time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='Prep time in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_collection', to='web.Collection'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='influencer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='influencer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
