# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20181109_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Collection')),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='eyebrow_title_influencer',
            field=models.CharField(default='', max_length=100, verbose_name='Eyebrow Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='eyebrow_title_product',
            field=models.CharField(default='', max_length=100, verbose_name='Eyebrow Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='eyebrow_title_recipe',
            field=models.CharField(default='', max_length=100, verbose_name='Eyebrow Title'),
        ),
        migrations.AddField(
            model_name='homepagecollection',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collections',
            field=models.ManyToManyField(through='web.HomepageCollection', to='web.Collection'),
        ),
    ]
