# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 23:44
from __future__ import unicode_literals

import apps.web.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20181109_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_hero', models.CharField(default='About Us', max_length=100, verbose_name='Hero Eyebrow Title')),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_subtitle', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=255)),
                ('main_copy', models.TextField(blank=True)),
                ('tile_set1_eyebrow', models.CharField(default='Our History', max_length=100, verbose_name='Top Tile Set Eyebrow Title')),
                ('tile_set1_title1', models.CharField(help_text='First half of title in gray', max_length=100, verbose_name='Top Tile Set Title 1')),
                ('tile_set1_title2', models.CharField(help_text='2nd half of title in yellow', max_length=100, verbose_name='Top Tile Set Title 2')),
                ('tile_set1_description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300, verbose_name='Top Tile Set Description')),
                ('tile_set1_cta_text', models.CharField(blank=True, max_length=100, verbose_name='Top Tile Set CTA Text')),
                ('tile_set1_cta_link', models.CharField(blank=True, max_length=255, verbose_name='Top Tile Set CTA Link')),
                ('tile_set1_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Top Tile Set Image')),
                ('tile_set2_eyebrow', models.CharField(default='Sustainability', max_length=100, verbose_name='Bottom Tile Set Eyebrow Title')),
                ('tile_set2_title1', models.CharField(help_text='First half of title in gray', max_length=100, verbose_name='Bottom Tile Set Title 1')),
                ('tile_set2_title2', models.CharField(help_text='2nd half of title in yellow', max_length=100, verbose_name='Bottom Tile Set Title 2')),
                ('tile_set2_description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300, verbose_name='Bottom Tile Set Description')),
                ('tile_set2_cta_text', models.CharField(blank=True, max_length=100, verbose_name='Bottom Tile Set CTA Text')),
                ('tile_set2_cta_link', models.CharField(blank=True, max_length=255, verbose_name='Bottom Tile Set CTA Link')),
                ('tile_set2_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bottom Tile Set Image')),
            ],
            options={
                'verbose_name': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300)),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='CTA Text')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('order', models.SmallIntegerField(default=0)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_cards', to='web.AboutUs')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
