# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 03:31
from __future__ import unicode_literals

import apps.web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_aboutus_aboutuscards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_title', models.CharField(default='Our Products', max_length=100, verbose_name='Hero Eyebrow Title')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('product_category_headline', models.CharField(max_length=150)),
                ('featured_eyebrow_title', models.CharField(blank=True, max_length=100)),
                ('featured_title1', models.CharField(blank=True, max_length=100)),
                ('featured_title2', models.CharField(blank=True, max_length=100)),
                ('featured_description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300)),
                ('featured_cta_text', models.CharField(blank=True, max_length=100, verbose_name='Featured CTA Text')),
                ('featured_link', models.CharField(blank=True, max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
