# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20181112_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNavCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Collection')),
            ],
            options={
                'verbose_name': 'Recipe Nav Collections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_recipe_eyebrow', models.CharField(blank=True, default='Featured Recipe', max_length=200)),
                ('featured_collection_eyebrow', models.CharField(blank=True, default='Featured Collection', max_length=200)),
                ('featured_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_collection', to='web.Collection')),
                ('featured_collections', models.ManyToManyField(through='web.RecipeNavCollection', to='web.Collection', verbose_name='Recipe Nav Collections')),
                ('featured_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_recipe', to='web.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipenavcollection',
            name='recipe_nav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.RecipeNavigation'),
        ),
        migrations.AlterUniqueTogether(
            name='recipenavcollection',
            unique_together=set([('recipe_nav', 'collection')]),
        ),
    ]
