# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20181112_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuscards',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name': 'Careers', 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ Section'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['-order'], 'verbose_name': 'FAQ Caregory', 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'ordering': ['-order'], 'verbose_name': 'Home Carousel', 'verbose_name_plural': 'Home Carousel Slides'},
        ),
        migrations.AlterModelOptions(
            name='homepagecollection',
            options={'ordering': ['-order'], 'verbose_name': 'Ready for a quick snack', 'verbose_name_plural': 'Ready for a quick snack'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='instructionstep',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='productdetailimage',
            options={'ordering': ['-order'], 'verbose_name': 'Product Detail Image', 'verbose_name_plural': 'Product Detail Images'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category__title', '-order'], 'verbose_name': 'Question', 'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='recipenavcollection',
            options={'ordering': ['-order'], 'verbose_name': 'Recipe Nav Collections'},
        ),
        migrations.AlterModelOptions(
            name='recipepagecollection',
            options={'ordering': ['-order'], 'verbose_name': 'Recipe Page Collections'},
        ),
        migrations.AlterModelOptions(
            name='recipepageherocollection',
            options={'ordering': ['-order'], 'verbose_name': 'Recipe Page Hero Collections'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-order'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured_on_landing',
        ),
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.SmallIntegerField(default=0, help_text='3rd product on homepage will be centered and highlighted'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='homepage_featured_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
