# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20181112_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuscards',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order'], 'verbose_name': 'FAQ Caregory', 'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'ordering': ['order'], 'verbose_name': 'Home Carousel', 'verbose_name_plural': 'Home Carousel Slides'},
        ),
        migrations.AlterModelOptions(
            name='homepagecollection',
            options={'ordering': ['order'], 'verbose_name': 'Ready for a quick snack', 'verbose_name_plural': 'Ready for a quick snack'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='instructionstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productdetailimage',
            options={'ordering': ['order'], 'verbose_name': 'Product Detail Image', 'verbose_name_plural': 'Product Detail Images'},
        ),
        migrations.AlterModelOptions(
            name='recipenavcollection',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Nav Collections'},
        ),
        migrations.AlterModelOptions(
            name='recipepagecollection',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Page Collections'},
        ),
        migrations.AlterModelOptions(
            name='recipepageherocollection',
            options={'ordering': ['order'], 'verbose_name': 'Recipe Page Hero Collections'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
