# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20181113_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(null=True, upload_to='')),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Our History Page',
                'verbose_name_plural': 'Our History Pages',
            },
        ),
        migrations.AlterModelOptions(
            name='historypage',
            options={'ordering': ['date'], 'verbose_name': 'Our History Event', 'verbose_name_plural': 'Our History Events'},
        ),
    ]
