# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20181113_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(null=True, upload_to='')),
                ('intro_text', models.TextField(blank=True)),
                ('side_bar_title', models.CharField(blank=True, max_length=100)),
                ('side_bar_text', models.TextField(blank=True)),
                ('side_bar_cta', models.CharField(blank=True, max_length=100)),
                ('side_bar_cta_link', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Us Page',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_cta',
            field=models.CharField(blank=True, default='', help_text='example: This product is available only in the US', max_length=255, verbose_name='Availability Disclaimer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='video_id',
            field=models.CharField(blank=True, default='', help_text='Video ID for video, e.g. https://www.youtube.com/watch?v=7NONdwbqRV8, id would be 7NONdwbqRV8', max_length=255),
            preserve_default=False,
        ),
    ]
