# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20181113_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='eyebrow_title',
            field=models.CharField(blank=True, default='Careers', max_length=100),
        ),
        migrations.AddField(
            model_name='careers',
            name='legal_header',
            field=models.CharField(blank='', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historyheader',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
