# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 00:38
from __future__ import unicode_literals

import apps.web.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20181114_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=400)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EcoStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('top_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('top_paragraphs', models.TextField(blank=True)),
                ('callout_text', apps.web.fields.CharFieldWithTextarea(blank=True, help_text='This is the text that is on the black background', max_length=300)),
                ('first_header', models.CharField(blank=True, max_length=200)),
                ('video_header', models.CharField(blank=True, max_length=200)),
                ('video_id', models.CharField(blank=True, help_text='Video ID for video, e.g. https://www.youtube.com/watch?v=7NONdwbqRV8, id would be 7NONdwbqRV8', max_length=255)),
                ('recycyle_header', models.CharField(blank=True, max_length=200)),
                ('recycyle_text', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300)),
                ('source_title', models.CharField(blank=True, default='Information Source:', max_length=100)),
                ('source_logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Sustainability Page',
            },
        ),
        migrations.AddField(
            model_name='ecostat',
            name='sustainability_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecostat_list', to='web.SustainabilityPage'),
        ),
        migrations.AddField(
            model_name='commitmentlistitem',
            name='sustainability_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_list', to='web.SustainabilityPage'),
        ),
    ]
