# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20181114_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereToBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
