# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_wheretobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
