# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_auto_20181116_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image should be 210x256', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
