# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_auto_20181124_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_title', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hero_paragraph', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Collection Landing Page',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category__title', 'order'], 'verbose_name': 'Question', 'verbose_name_plural': 'FAQ Questions'},
        ),
        migrations.AddField(
            model_name='product',
            name='homepage_cta',
            field=models.CharField(blank=True, default='Learn More', help_text="'Learn More` CTA Use in featured recipes and featured products section of homepage", max_length=150, verbose_name='Homepage Product CTA'),
        ),
        migrations.AlterField(
            model_name='aboutuscards',
            name='order',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='order',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='commitmentlistitem',
            name='order',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='ecostat',
            name='order',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='homepagecollection',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_order',
            field=models.SmallIntegerField(default=100, help_text='3rd product on homepage will be centered and highlighted'),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='homepage_featured_order',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='recipenavcollection',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='recipepagecollection',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='recipepageherocollection',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
