# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 22:04
from __future__ import unicode_literals

import apps.web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20181127_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300)),
                ('meta_keywords', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=300)),
                ('meta_og_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(help_text='Only used within Admin', max_length=200)),
                ('slug', models.SlugField(help_text='the url of the page')),
                ('head_content', models.TextField(blank=True)),
                ('body_class', models.CharField(blank=True, help_text='set class of body tag', max_length=150)),
                ('js_content', models.TextField(blank=True, help_text='added to end of page with other javascript content')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
