# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 22:40
from __future__ import unicode_literals

import apps.web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_campaignpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='careers',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='careers',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='collectionlandingpage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='collectionlandingpage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='faq',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='faq',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historyheader',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='historyheader',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productpage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='productpage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recipelandingpage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='recipelandingpage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sustainabilitypage',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='sustainabilitypage',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wheretobuy',
            name='meta_og_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='wheretobuy',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='careers',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='careers',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='collectionlandingpage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='collectionlandingpage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='faq',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='faq',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='historyheader',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='historyheader',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='recipelandingpage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='recipelandingpage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='meta_description',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='meta_keywords',
            field=apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320),
        ),
    ]
