# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_auto_20181127_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelatedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Recipe')),
            ],
            options={
                'verbose_name': 'Related Recipes',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='related_recipes',
            field=models.ManyToManyField(related_name='product_related_recipes', through='web.ProductRelatedRecipe', to='web.Recipe', verbose_name='Related Recipes'),
        ),
        migrations.AlterUniqueTogether(
            name='productrelatedrecipe',
            unique_together=set([('recipe', 'product')]),
        ),
    ]
