# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_auto_20181127_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_recipe_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
