# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_product_related_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypage',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Show just year i.e 2018'), (2, 'Show just month i.e January'), (3, 'Show month and year i.e Jan, 2018'), (0, 'Hide date and dot')], default=1),
        ),
    ]
