# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_auto_20181205_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpage',
            name='slug',
            field=models.SlugField(help_text='the url of the page', max_length=75),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=75),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=75),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='slug',
            field=models.SlugField(max_length=75),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=75),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=75),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
    ]
