# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_auto_20181212_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
