# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_auto_20190205_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypage',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Show just year i.e 2018'), (2, 'Show just month i.e January'), (3, 'Show month and year i.e Jan, 2018'), (4, 'Show month, day, then year'), (0, 'Hide date and dot')], default=1),
        ),
        migrations.AlterField(
            model_name='historypage',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
