# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_auto_20190205_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypage',
            name='category',
            field=models.CharField(choices=[('none', '-'), ('us', 'US'), ('world', 'World')], default='none', help_text='Set category to determine if the article belongs in US or Around the Globe carousel, leave default to populate article under Mission News', max_length=100),
        ),
        migrations.AlterField(
            model_name='historypage',
            name='description',
            field=models.TextField(blank=True, help_text='Limit description to around 350 characters (including whitespace)', max_length=450, null=True),
        ),
    ]
