# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_auto_20190207_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='floodlight_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='floodlight_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='floodlight_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
