# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_auto_20190213_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='floodlight_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
