# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 20:32
from __future__ import unicode_literals

from django.db import migrations
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_remove_subcategory_floodlight_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, upload_to='', verbose_name='Hero Image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='tile_set1_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='', verbose_name='Top Tile Set Image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='tile_set2_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='', verbose_name='Bottom Tile Set Image'),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='careers',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Image should be 210x256', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='marquee_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Marquee Image for Category page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Marquee Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collectionlandingpage',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collectionlandingpage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faq',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historyheader',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historyheader',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historypage',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='background_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Background image of carousel slide', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_influencer_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Marquee Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Primary product image used on detail and landing pages', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_facts',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Used to display nutritional facts label', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='image',
            field=optimized_image.fields.OptimizedImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='featured_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Marquee Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='influencer_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_facts',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Used to display nutritional facts label', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Poster image for video. If empty, you tube defaul image is used', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipelandingpage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='list_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Image used in product categories page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='source_logo',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='top_logo',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sustainabilitypage',
            name='video_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Poster image for video. If empty, you tube defaul image is used', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='hero_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='meta_og_image',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
