# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 20:17
from __future__ import unicode_literals

import apps.web.fields
from django.db import migrations, models
import django.db.models.deletion
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_product_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicCampaignAdditionalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_label', models.CharField(default='Learn More', help_text='Text to use in the CTA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCampaignHeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', optimized_image.fields.OptimizedImageField(blank=True, help_text='Background image of carousel slide', null=True, upload_to='')),
                ('image_alt_text', models.CharField(help_text='Text to use when image is not loaded', max_length=200)),
                ('cta_button_label', models.CharField(help_text='Text to use inside the CTA button', max_length=50)),
                ('cta_button_link', models.CharField(help_text='Text to use as CTA button action', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCampaignHighlightedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_label', models.CharField(default='Visit', help_text='Text to use for the link', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCampaignInfluencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', optimized_image.fields.OptimizedImageField(blank=True, help_text='Influencer image', null=True, upload_to='')),
                ('image_alt_text', models.CharField(help_text='Text to use when image is not loaded', max_length=200)),
                ('blog_title', models.CharField(help_text='Blog title for the influencer', max_length=200)),
                ('recipe_title', models.CharField(help_text='Recipe title for the influencer', max_length=200)),
                ('button_label', models.CharField(help_text='Text to use in the button', max_length=50)),
                ('button_link', models.CharField(help_text='Link to use in the button', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCampaignPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320)),
                ('meta_keywords', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320)),
                ('meta_og_image', optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to='')),
                ('meta_og_title', models.CharField(blank=True, max_length=150)),
                ('meta_og_description', apps.web.fields.CharFieldWithTextarea(blank=True, max_length=320)),
                ('title', models.CharField(help_text='Campaign title', max_length=200)),
                ('slug', models.SlugField(help_text='Friendly campaign identifier in the url path', max_length=75)),
                ('hero_section_is_visible', models.BooleanField(default=True, help_text='Check if hero section should be visible in dynamic campaign page')),
                ('highlighted_products_section_is_visible', models.BooleanField(default=True, help_text='Check if highlighted products section should be visible in dynamic campaign page')),
                ('highlighted_products_section_title', models.CharField(default='Highlighted Products', help_text='Highlighted products section title', max_length=200)),
                ('highlighted_products_section_description', models.CharField(default='Highlighted Products', help_text='Highlighted products section description', max_length=200)),
                ('additional_products_section_is_visible', models.BooleanField(default=True, help_text='Check if additional products section should be visible in dynamic campaign page')),
                ('additional_products_section_title', models.CharField(default='Additional Products', help_text='Additional products section title', max_length=200)),
                ('find_a_store_section_is_visible', models.BooleanField(default=True, help_text='Check if find a store section should be visible in dynamic campaign page')),
                ('influencers_section_is_visible', models.BooleanField(default=True, help_text='Check if influencers section should be visible in dynamic campaign page')),
                ('influencers_section_title', models.CharField(default='Influencers', help_text='Influencers section title', max_length=200)),
                ('influencers_section_description', models.CharField(default='Influencers', help_text='Influencers section description', max_length=200)),
                ('recipes_section_is_visible', models.BooleanField(default=True, help_text='Check if recipes section should be visible in dynamic campaign page')),
                ('recipes_section_title', models.CharField(default='Recipes', help_text='Recipes section title', max_length=200)),
                ('recipes_section_description', models.CharField(default='Recipes', help_text='Recipes section description', max_length=200)),
                ('recipes_section_button_label', models.CharField(default='Recipes', help_text='Recipes section button label', max_length=200)),
                ('recipes_section_button_link', models.CharField(default='Recipes', help_text='Recipes section button link', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicCampaignRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_campaign_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DynamicCampaignPage')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='dynamiccampaigninfluencer',
            name='dynamic_campaign_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DynamicCampaignPage'),
        ),
        migrations.AddField(
            model_name='dynamiccampaignhighlightedproduct',
            name='dynamic_campaign_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DynamicCampaignPage'),
        ),
        migrations.AddField(
            model_name='dynamiccampaignhighlightedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
        migrations.AddField(
            model_name='dynamiccampaignheroimage',
            name='dynamic_campaign_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DynamicCampaignPage'),
        ),
        migrations.AddField(
            model_name='dynamiccampaignadditionalproduct',
            name='dynamic_campaign_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DynamicCampaignPage'),
        ),
        migrations.AddField(
            model_name='dynamiccampaignadditionalproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
    ]
